//
// Created by ta11e4rand on 19/11/15.
//

#ifndef DETECTION_AND_TRACKING_OPTICALFLOWMAIN_H
#define DETECTION_AND_TRACKING_OPTICALFLOWMAIN_H


int opticalFlowMain();


#endif //DETECTION_AND_TRACKING_OPTICALFLOWMAIN_H
